import type { ComponentType } from 'react';
import {
  InvoiceDesign1,
  InvoiceDesign1Blank,
  InvoiceDesign2,
  InvoiceDesign2Blank,
  InvoiceDesign3,
  InvoiceDesign3Blank,
  InvoiceDesign4,
  InvoiceDesign4Blank,
  InvoiceDesign5,
  InvoiceDesign5Blank,
} from '../reference/invoices';
import type { InvoicePrintData, PrintTemplateComponent, PrintTemplateDefinition } from './types';

function invoiceTemplate(
  c: ComponentType<{ data?: InvoicePrintData }>,
): PrintTemplateComponent {
  return c as unknown as PrintTemplateComponent;
}

export const invoiceTemplateDefinitions: PrintTemplateDefinition[] = [
  {
    id: 'invoice-design-1',
    category: 'invoice',
    nameAr: 'فاتورة – تصميم ١',
    nameEn: 'Invoice – Design 1',
    variant: 'original',
    language: 'bilingual',
    supports: { plainA4: true, letterhead: false },
    component: invoiceTemplate(InvoiceDesign1),
    sourceFile: 'docs/invoice_templates/html/design1.html',
  },
  {
    id: 'invoice-design-1-blank',
    category: 'invoice',
    nameAr: 'فاتورة – تصميم ١ (ترويسة مطبوعة)',
    nameEn: 'Invoice – Design 1 (Letterhead)',
    variant: 'blank-letterhead',
    language: 'bilingual',
    supports: { plainA4: false, letterhead: true },
    component: invoiceTemplate(InvoiceDesign1Blank),
    sourceFile: 'docs/invoice_templates/html/design1_blank.html',
  },
  {
    id: 'invoice-design-2',
    category: 'invoice',
    nameAr: 'فاتورة – تصميم ٢',
    nameEn: 'Invoice – Design 2',
    variant: 'original',
    language: 'bilingual',
    supports: { plainA4: true, letterhead: false },
    component: invoiceTemplate(InvoiceDesign2),
    sourceFile: 'docs/invoice_templates/html/design2.html',
  },
  {
    id: 'invoice-design-2-blank',
    category: 'invoice',
    nameAr: 'فاتورة – تصميم ٢ (ترويسة مطبوعة)',
    nameEn: 'Invoice – Design 2 (Letterhead)',
    variant: 'blank-letterhead',
    language: 'bilingual',
    supports: { plainA4: false, letterhead: true },
    component: invoiceTemplate(InvoiceDesign2Blank),
    sourceFile: 'docs/invoice_templates/html/design2_blank.html',
  },
  {
    id: 'invoice-design-3',
    category: 'invoice',
    nameAr: 'فاتورة – تصميم ٣',
    nameEn: 'Invoice – Design 3',
    variant: 'original',
    language: 'bilingual',
    supports: { plainA4: true, letterhead: false },
    component: invoiceTemplate(InvoiceDesign3),
    sourceFile: 'docs/invoice_templates/html/design3.html',
  },
  {
    id: 'invoice-design-3-blank',
    category: 'invoice',
    nameAr: 'فاتورة – تصميم ٣ (ترويسة مطبوعة)',
    nameEn: 'Invoice – Design 3 (Letterhead)',
    variant: 'blank-letterhead',
    language: 'bilingual',
    supports: { plainA4: false, letterhead: true },
    component: invoiceTemplate(InvoiceDesign3Blank),
    sourceFile: 'docs/invoice_templates/html/design3_blank.html',
  },
  {
    id: 'invoice-design-4',
    category: 'invoice',
    nameAr: 'فاتورة – تصميم ٤',
    nameEn: 'Invoice – Design 4',
    variant: 'original',
    language: 'bilingual',
    supports: { plainA4: true, letterhead: false },
    component: invoiceTemplate(InvoiceDesign4),
    sourceFile: 'docs/invoice_templates/html/design4.html',
  },
  {
    id: 'invoice-design-4-blank',
    category: 'invoice',
    nameAr: 'فاتورة – تصميم ٤ (ترويسة مطبوعة)',
    nameEn: 'Invoice – Design 4 (Letterhead)',
    variant: 'blank-letterhead',
    language: 'bilingual',
    supports: { plainA4: false, letterhead: true },
    component: invoiceTemplate(InvoiceDesign4Blank),
    sourceFile: 'docs/invoice_templates/html/design4_blank.html',
    notes: 'Blank variant hides .strip (header bar) instead of .head — structural equivalent.',
  },
  {
    id: 'invoice-design-5',
    category: 'invoice',
    nameAr: 'فاتورة – تصميم ٥',
    nameEn: 'Invoice – Design 5',
    variant: 'original',
    language: 'bilingual',
    supports: { plainA4: true, letterhead: false },
    component: invoiceTemplate(InvoiceDesign5),
    sourceFile: 'docs/invoice_templates/html/design5.html',
  },
  {
    id: 'invoice-design-5-blank',
    category: 'invoice',
    nameAr: 'فاتورة – تصميم ٥ (ترويسة مطبوعة)',
    nameEn: 'Invoice – Design 5 (Letterhead)',
    variant: 'blank-letterhead',
    language: 'bilingual',
    supports: { plainA4: false, letterhead: true },
    component: invoiceTemplate(InvoiceDesign5Blank),
    sourceFile: 'docs/invoice_templates/html/design5_blank.html',
  },
];
