import type { ComponentType } from 'react';
import {
  QuotationDesign1, QuotationDesign1Blank,
  QuotationDesign2, QuotationDesign2Blank,
  QuotationDesign3, QuotationDesign3Blank,
  QuotationDesign4, QuotationDesign4Blank,
  QuotationDesign5, QuotationDesign5Blank,
} from '../reference/quotations';
import type { PrintTemplateComponent, PrintTemplateDefinition, QuotationPrintData } from './types';

function quotationTemplate(
  c: ComponentType<{ data?: QuotationPrintData }>
): PrintTemplateComponent {
  return c as unknown as PrintTemplateComponent;
}

export const quotationTemplateDefinitions: PrintTemplateDefinition[] = [
  {
    id: 'quotation-design-1',
    category: 'quotation',
    nameAr: 'عرض سعر – كلاسيكي رسمي',
    nameEn: 'Quotation – Classic Formal',
    variant: 'original',
    language: 'bilingual',
    supports: { plainA4: true, letterhead: false },
    component: quotationTemplate(QuotationDesign1),
    sourceFile: 'docs/new q/quotation-template-01-with-letterhead.html',
  },
  {
    id: 'quotation-design-1-blank',
    category: 'quotation',
    nameAr: 'عرض سعر – كلاسيكي رسمي (ترويسة مطبوعة)',
    nameEn: 'Quotation – Classic Formal (Pre-printed Letterhead)',
    variant: 'blank-letterhead',
    language: 'bilingual',
    supports: { plainA4: false, letterhead: true },
    component: quotationTemplate(QuotationDesign1Blank),
    sourceFile: 'docs/new q/quotation-template-01-blank-letterhead.html',
  },
  {
    id: 'quotation-design-2',
    category: 'quotation',
    nameAr: 'عرض سعر – تنفيذي فاخر',
    nameEn: 'Quotation – Executive',
    variant: 'original',
    language: 'bilingual',
    supports: { plainA4: true, letterhead: false },
    component: quotationTemplate(QuotationDesign2),
    sourceFile: 'docs/new q/quotation-template-02-with-letterhead.html',
  },
  {
    id: 'quotation-design-2-blank',
    category: 'quotation',
    nameAr: 'عرض سعر – تنفيذي فاخر (ترويسة مطبوعة)',
    nameEn: 'Quotation – Executive (Pre-printed Letterhead)',
    variant: 'blank-letterhead',
    language: 'bilingual',
    supports: { plainA4: false, letterhead: true },
    component: quotationTemplate(QuotationDesign2Blank),
    sourceFile: 'docs/new q/quotation-template-02-blank-letterhead.html',
  },
  {
    id: 'quotation-design-3',
    category: 'quotation',
    nameAr: 'عرض سعر – Minimal حديث',
    nameEn: 'Quotation – Modern Minimal',
    variant: 'original',
    language: 'bilingual',
    supports: { plainA4: true, letterhead: false },
    component: quotationTemplate(QuotationDesign3),
    sourceFile: 'docs/new q/quotation-template-03-with-letterhead.html',
  },
  {
    id: 'quotation-design-3-blank',
    category: 'quotation',
    nameAr: 'عرض سعر – Minimal حديث (ترويسة مطبوعة)',
    nameEn: 'Quotation – Modern Minimal (Pre-printed Letterhead)',
    variant: 'blank-letterhead',
    language: 'bilingual',
    supports: { plainA4: false, letterhead: true },
    component: quotationTemplate(QuotationDesign3Blank),
    sourceFile: 'docs/new q/quotation-template-03-blank-letterhead.html',
  },
  {
    id: 'quotation-design-4',
    category: 'quotation',
    nameAr: 'عرض سعر – Corporate Clean',
    nameEn: 'Quotation – Corporate Clean',
    variant: 'original',
    language: 'bilingual',
    supports: { plainA4: true, letterhead: false },
    component: quotationTemplate(QuotationDesign4),
    sourceFile: 'docs/new q/quotation-template-04-with-letterhead.html',
  },
  {
    id: 'quotation-design-4-blank',
    category: 'quotation',
    nameAr: 'عرض سعر – Corporate Clean (ترويسة مطبوعة)',
    nameEn: 'Quotation – Corporate Clean (Pre-printed Letterhead)',
    variant: 'blank-letterhead',
    language: 'bilingual',
    supports: { plainA4: false, letterhead: true },
    component: quotationTemplate(QuotationDesign4Blank),
    sourceFile: 'docs/new q/quotation-template-04-blank-letterhead.html',
  },
  {
    id: 'quotation-design-5',
    category: 'quotation',
    nameAr: 'عرض سعر – جدول احترافي',
    nameEn: 'Quotation – Professional Table',
    variant: 'original',
    language: 'bilingual',
    supports: { plainA4: true, letterhead: false },
    component: quotationTemplate(QuotationDesign5),
    sourceFile: 'docs/new q/quotation-template-05-with-letterhead.html',
  },
  {
    id: 'quotation-design-5-blank',
    category: 'quotation',
    nameAr: 'عرض سعر – جدول احترافي (ترويسة مطبوعة)',
    nameEn: 'Quotation – Professional Table (Pre-printed Letterhead)',
    variant: 'blank-letterhead',
    language: 'bilingual',
    supports: { plainA4: false, letterhead: true },
    component: quotationTemplate(QuotationDesign5Blank),
    sourceFile: 'docs/new q/quotation-template-05-blank-letterhead.html',
  },
];
